### ISSUE TITLE
Can't start the app using expo

### ISSUE THREAD

**Issue by ahmadx87** [tomekz/viennaBike-native#5]
Hi Tomasz,
I got your app from play store. Thank you for open sourcing your app. I've just started learning react native. I want to learn from your and other open source apps. I want to run the app using expo but I don't know how. I downloaded the repo and extracted to a folder named say "viennabike" then on the parent folder I ran `create-react-native-app viennabike` but I got this error `The directory 'viennabike' contains file(s) that could conflict. Aborting.`
Could you please tell me what I should do?

**Comment by tomekz** [comment]
Hi and thanks a lot for your input. Since v2.0.0 I've ejected the project from  _create-react-native-app_  and _expo SDK_ for the reasons I've documented [here](https://stackoverflow.com/a/45978865/7000332) 
This means you can't run the app using expo anymore and you have to setup whole dev environment including React Native CLI and Android Studio. This will then allow you to launch it on the emulator or directly on your plugged mobile device

To setup the dev env please follow the guide from React Native [docs](https://facebook.github.io/react-native/releases/next/docs/getting-started.html) (Open 'Building Projects with Native Code' tab and choose Android as Target OS and your respective operating system as Development OS )

**Comment by tomekz** [comment]
Updated README.md f19f3186beb8ec024cf17462133f0739c87e3fca
